### ISSUE TITLE
DomainType for DomainSelectionProof and DomainAggregateAndProof

### ISSUE THREAD

**Issue by BisonDee** [wealdtech/go-eth2-types#1]
I noticed that the type for `DomainSelectionProof ` and `DomainAggregateAndProof` are `[]byte` rather than `DomainType`. Is this on purpose?

**Comment by mcdee** [comment]
Doesn't sound like it.  Where are you seeing this?

**Comment by BisonDee** [comment]
I thought I pasted in the link, but nope :). Its here
https://github.com/wealdtech/go-eth2-types/blob/master/domain.go#L39

**Comment by mcdee** [comment]
Thanks, I'll update and push a v2.5.4 that will have the fix.
