### ISSUE TITLE
Release tag v2.x

### ISSUE THREAD

**Issue by ctrl-alt-lulz** [wealdtech/go-eth2-types#3]
@mcdee would you mind pushing a new release tag? that way I can access the new signature domains with a versioned tag

eg needed to get latest domains
	github.com/wealdtech/go-eth2-types v1.0.0

to
	github.com/wealdtech/go-eth2-types/v2 v2.6.0->v.3.0.0 or v.2.70
	
not sure if you do the majors on forks, but I think either would capture it

**Comment by mcdee** [comment]
The domains should be available with v2.6.0 (assuming you mean `DomainSyncCommittee` and the like).

**Comment by mcdee** [comment]
Closed due to inactivity.
